# Generated by Django 4.1.7 on 2023-03-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(max_length=128, verbose_name='confirm_password'),
        ),
    ]
